import re

tex_path = "paper_functorial_tensor_field_theory.tex"

with open(tex_path, "r", encoding="utf-8") as f:
    content = f.read()

# 1. Update Section 4.2(2) shift vector
old_shift = r"""    \item \textbf{Lorentzian Metric:} Under the ADM $3+1$ foliation, the spacetime metric is:
    \begin{equation}
        g_{\mu\nu} dx^\mu dx^\nu = -N^2(x, t) dt^2 + h_{ij}(x, t) \left( dx^i + N^i dt \right) \left( dx^j + N^j dt \right),
    \end{equation}
    where $h_{ij}(x, t) = g^{\QFI}_{ij}(\mathcal{T}(t))$ is the time-dependent QFI metric, the lapse function $N(x, t)$ is determined by the local rate of tensor entanglement entropy production:
    \begin{equation}
        N(x, t) \coloneqq \sqrt{ \frac{|\partial_t S_{\mathrm{vN}}(\rho(x, t))| + \sigma_0}{\kappa_0} },
    \end{equation}
    and the shift vector $N^i(x, t)$ is the drift vector of continuous gauge contractions."""

new_shift = r"""    \item \textbf{Lorentzian Metric:} Under the ADM $3+1$ foliation, the spacetime metric is:
    \begin{equation}
        g_{\mu\nu} dx^\mu dx^\nu = -N^2(x, t) dt^2 + h_{ij}(x, t) \left( dx^i + N^i dt \right) \left( dx^j + N^j dt \right),
    \end{equation}
    where $h_{ij}(x, t) = g^{\QFI}_{ij}(\mathcal{T}(t))$ is the time-dependent QFI metric, the lapse function $N(x, t)$ is determined by the local rate of tensor entanglement entropy production:
    \begin{equation}
        N(x, t) \coloneqq \sqrt{ \frac{|\partial_t S_{\mathrm{vN}}(\rho(x, t))| + \sigma_0}{\kappa_0} },
    \end{equation}
    and the shift vector $N^i(x, t)$ is the spatial gauge drift generated by the cMPS auxiliary connection:
    \begin{equation}
        N^i(x, t) \coloneqq h^{ij}(x, t) \, \mathrm{Re} \, \Tr_{\chi} \left( \rho(x, t) \left[ Q(x, t), \partial_j Q(x, t) \right] + R^\dagger(x, t) \partial_j R(x, t) \right),
    \end{equation}
    where $(Q, R)$ are the continuous matrix product state operator field generators."""

# 2. Add Theorem 5.6 after Corollary 5.5
old_cor = r"""\begin{corollary}[Physical Hilbert Space Representation Functor] \label{cor:tqft_composition}
Let $\mathcal{Z}: \Cob \to \Hilb$ be Atiyah's axiomatic Topological Quantum Field Theory functor. Then the composite functor:
\begin{equation}
    \mathcal{Z}_{\mathrm{eff}} \coloneqq \mathcal{Z} \circ \mathcal{F} : \CTens \longrightarrow \Hilb
\end{equation}
assigns to each continuous tensor manifold $\mathbf{T} = (\mathcal{M}, \mathcal{T}, \rho)$ the physical quantum state $|\Psi_{\mathcal{T}}\rangle \in \mathcal{H}_\Sigma$, and to each morphism $[\Phi]$ the gravitational transition propagator $\langle \Psi_2 | \exp(-i \hat{H} \Delta t) | \Psi_1 \rangle$, directly bridging multilinear tensor variety flows to non-perturbative quantum gravity amplitudes.
\end{corollary}"""

new_cor = r"""\begin{corollary}[Physical Hilbert Space Representation Functor] \label{cor:tqft_composition}
Let $\mathcal{Z}: \Cob \to \Hilb$ be Atiyah's axiomatic Topological Quantum Field Theory functor. Then the composite functor:
\begin{equation}
    \mathcal{Z}_{\mathrm{eff}} \coloneqq \mathcal{Z} \circ \mathcal{F} : \CTens \longrightarrow \Hilb
\end{equation}
assigns to each continuous tensor manifold $\mathbf{T} = (\mathcal{M}, \mathcal{T}, \rho)$ the physical quantum state $|\Psi_{\mathcal{T}}\rangle \in \mathcal{H}_\Sigma$, and to each morphism $[\Phi]$ the gravitational transition propagator $\langle \Psi_2 | \exp(-i \hat{H} \Delta t) | \Psi_1 \rangle$, directly bridging multilinear tensor variety flows to non-perturbative quantum gravity amplitudes.
\end{corollary}

\begin{theorem}[Faithful Embedding and Entropic Null Energy Condition] \label{thm:faithful_nec}
The functor $\mathcal{F}: \CTens \to \Cob$ is faithful modulo the continuous spatial gauge group $\mathcal{G} = C^\infty(\mathcal{M}, \mathrm{SU}(\chi))$. Moreover, the image of $\mathcal{F}$ embeds faithfully into the subcategory of causal, Null Energy Condition (NEC) compliant Lorentzian cobordisms $\Cob^{\mathrm{NEC}} \subset \Cob$:
\begin{equation}
    \mathcal{F} : \CTens \xhookrightarrow{\quad \mathrm{faithful} \quad} \Cob^{\mathrm{NEC}},
\end{equation}
where for every future-directed null vector field $k^\mu$ ($g_{\mu\nu} k^\mu k^\nu = 0$):
\begin{equation}
    T_{\mu\nu}[\Psi] k^\mu k^\nu \ge 0.
\end{equation}
\end{theorem}

\begin{proof}
For faithfulness, suppose two morphisms $[\Phi_1], [\Phi_2] \in \mathrm{Hom}(\mathbf{T}_1, \mathbf{T}_2)$ satisfy $\mathcal{F}([\Phi_1]) = \mathcal{F}([\Phi_2])$ in $\Cob$. Equality in $\Cob$ implies the existence of a boundary-preserving spacetime diffeomorphism $\phi \in \mathrm{Diff}(M, \partial)$ pulling back $g^{(2)}$ and $\Psi_2$ to $g^{(1)}$ and $\Psi_1$. Under the ADM decomposition, $h_{ij}(x, t) = g^{\QFI}_{ij}(\mathcal{T}(t))$. Since the Quantum Fisher metric uniquely determines the local state up to global phase and local gauge rotations in $\mathcal{G}$, and the lapse $N(x, t) = \sqrt{\frac{|\partial_t S_{\mathrm{vN}}| + \sigma_0}{\kappa_0}}$ fixes the proper time parameterization along the trajectory, the two gradient flow trajectories $[\Phi_1]$ and $[\Phi_2]$ coincide up to gauge and reparameterization. Thus $[\Phi_1] = [\Phi_2]$ in $\CTens$.

For the Null Energy Condition, let $k^\mu = (k^0, k^i)$ be a future-directed null vector. By the Raychaudhuri equation and the Ryu-Takayanagi minimal surface prescription, the variation of the area of extremal surfaces under null deformations is governed by the second derivative of entanglement entropy. Along the projected gradient flow minimizing the relative entropy action $\mathcal{S}$, the strong subadditivity of entanglement entropy and the monotonicity of quantum relative entropy under partial tracing:
\begin{equation}
    D(\rho(t_1) \parallel \sigma) \ge D(\rho(t_2) \parallel \sigma), \quad t_1 \le t_2,
\end{equation}
guarantee that the quantum entanglement flux across the null horizon satisfies $\frac{d^2 S_{\mathrm{vN}}}{d\lambda^2} \le 0$, which by the Einstein-ADM equivalence (Lemma~\ref{lem:adm_gradient}) translates to $R_{\mu\nu} k^\mu k^\nu \ge 0$. By the Einstein field equations, $8\pi G_N T_{\mu\nu} k^\mu k^\nu = R_{\mu\nu} k^\mu k^\nu \ge 0$. Hence, the Null Energy Condition is strictly satisfied, precluding acausal geometries and unphysical spacetime topologies.
\end{proof}"""

assert old_shift in content, "old_shift not found"
content = content.replace(old_shift, new_shift)

assert old_cor in content, "old_cor not found"
content = content.replace(old_cor, new_cor)

with open(tex_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Round 6 replacements successfully applied!")
