"""Ramo E, via 2: can the signed-permutation group B3 of Delta_2 give a non-trivial CKM? (draft, unverified)

Setup: residual symmetry approach. Up and down sectors keep abelian subgroups H_u, H_d of B3
(48 signed permutations of the 3 vertices): H^dagger (M M^dagger) H = M M^dagger.
If the subgroup fixes the eigenbasis (all joint eigenspaces 1-dim), |V| = |U_u^dagger U_d| is
fixed up to row/column order. We list every fixed |V| and compare with data.
If a subgroup leaves a 2-dim eigenspace, one angle is free (no prediction of it).

Data (PDG 2024, CHECK before citing): |Vus| = 0.2243(8), |Vcb| = 0.0410(14), |Vub| = 0.00382(20).
Oracle: circulant (Z3) in both sectors gives V = 1 (paper, Remark on the DFT); Z3 against the
  diagonal Klein group gives |V_ij| = 1/sqrt3 (DFT moduli), computed by hand.
Negative control: an arbitrary non-symmetric pair of unitaries gives no fixed |V|.
"""
import itertools
import numpy as np

rng = np.random.default_rng(7)
DATA = np.array([[0.97435, 0.2243, 0.00382], [0.2242, 0.97349, 0.0410], [0.00857, 0.0404, 0.99912]])
ERR = np.array([[0.0002, 0.0008, 0.0002], [0.0008, 0.0002, 0.0014], [0.0002, 0.0008, 0.0001]])

els = []
for perm in itertools.permutations(range(3)):
    for sg in itertools.product([1, -1], repeat=3):
        G = np.zeros((3, 3))
        for i, j in enumerate(perm):
            G[i, j] = sg[i]
        els.append(G)


def key(M):
    return tuple(np.round(M, 6).ravel())


def generated(gens):
    S = {key(np.eye(3)): np.eye(3)}
    frontier = [np.eye(3)]
    while frontier:
        new = []
        for A in frontier:
            for g in gens:
                B = A @ g
                k = key(B)
                if k not in S:
                    S[k] = B
                    new.append(B)
        frontier = new
    return list(S.values())


def abelian(H):
    return all(np.allclose(a @ b, b @ a) for a in H for b in H)


# abelian subgroups generated by one or two elements, modulo equality
subgroups = {}
for g1, g2 in itertools.combinations_with_replacement(range(len(els)), 2):
    H = generated([els[g1], els[g2]])
    if abelian(H):
        subgroups[frozenset(key(h) for h in H)] = H


def random_invariant(H):
    X = rng.normal(size=(3, 3)) + 1j * rng.normal(size=(3, 3))
    X = X @ X.conj().T
    return sum(h.T @ X @ h for h in H) / len(H)


def eigbasis(M):
    return np.linalg.eigh(M)[1]


def fixes_basis(H):
    Us = [eigbasis(random_invariant(H)) for _ in range(3)]
    ref = np.abs(Us[0].conj().T @ Us[1])
    return np.allclose(np.sort(ref.ravel()), np.sort(np.eye(3).ravel()), atol=1e-8)


full = [H for H in subgroups.values() if fixes_basis(H)]
print(f"abelian subgroups of B3: {len(subgroups)}; fixing the eigenbasis completely: {len(full)}")


def best_perm_chi2(A):
    best = (np.inf, None)
    for r in itertools.permutations(range(3)):
        for c in itertools.permutations(range(3)):
            B = A[list(r)][:, list(c)]
            chi = (((B - DATA) / ERR) ** 2).sum()
            if chi < best[0]:
                best = (chi, B)
    return best


patterns = {}
for Hu, Hd in itertools.product(full, repeat=2):
    Vs = [np.abs(eigbasis(random_invariant(Hu)).conj().T @ eigbasis(random_invariant(Hd))) for _ in range(2)]
    pat = tuple(sorted(np.round(Vs[0], 5).ravel()))
    assert pat == tuple(sorted(np.round(Vs[1], 5).ravel())), "pattern not fixed"
    patterns.setdefault(pat, Vs[0])

print(f"distinct fixed |V| patterns: {len(patterns)}")
for pat, V in patterns.items():
    chi, B = best_perm_chi2(V)
    vus = sorted(set(np.round(V.ravel(), 4)))
    print(f"  moduli {vus}: best chi2 = {chi:.3g}")

# Partial residual symmetry: Z2 in one sector -> one free angle; can Cabibbo be *predicted*?
print("\nOne sector with residual Z2 only (2-dim eigenspace): the angle in that plane is a free parameter,")
print("so |Vus| is fitted, not predicted. No zero-parameter Cabibbo angle arises from B3.")

# Oracles
w = np.exp(2j * np.pi / 3)
F = np.array([[1, 1, 1], [1, w, w**2], [1, w**2, w]]) / np.sqrt(3)
Z3 = generated([np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]], float)])
K = generated([np.diag([1., -1, -1]), np.diag([-1., 1, -1])])
V_cc = np.abs(eigbasis(random_invariant(Z3)).conj().T @ eigbasis(random_invariant(Z3)))
V_ck = np.abs(eigbasis(random_invariant(Z3)).conj().T @ eigbasis(random_invariant(K)))
print("\noracle circulant-circulant is a permutation matrix:", np.allclose(np.sort(V_cc.ravel()), np.sort(np.eye(3).ravel())))
print("oracle circulant-Klein all 1/sqrt3:", np.allclose(V_ck, 1 / np.sqrt(3)))

# Negative control
A = np.linalg.qr(rng.normal(size=(3, 3)) + 1j * rng.normal(size=(3, 3)))[0]
B = np.linalg.qr(rng.normal(size=(3, 3)) + 1j * rng.normal(size=(3, 3)))[0]
chi, _ = best_perm_chi2(np.abs(A.conj().T @ B))
print(f"negative control, random unitaries: chi2 = {chi:.3g} (must be large)")
